
defaults:
  metadata:
    author: 'Markizano Draconus'
    credits: Captions by Whisper from OpenAI
    website: "https://markizano.net/"
    twitter: "@Markizano"
    youtube: "@KizanosFinTech"
    blog: "https://blog.markizano.net/"

  filter_complex:
    - "[0:v]scale=720x1280,pad=864:1536:72:80,scale=720x1280,setsar=1:1,subtitles=resources/bash-pipelines.srt:force_style='FontName=Impact,OutlineColour=&H40000000,BorderStyle=3'[_v]"
    - "[1:v]format=yuv420p,setpts=PTS-STARTPTS,fade=in:st=0:d=1:alpha=1,fade=out:st=4:d=1:alpha=1[disclaim]"
    - "[_v][disclaim]overlay=W-w-100:0:enable='between(t,0,5)',setpts=PTS-STARTPTS[video]"
    - "[0:a]volume=1.5,afftdn=nr=10:nf=-20:tn=1,equalizer=f=623:w=3.5:t=h:g=-15:n=1,asetpts=NB_CONSUMED_SAMPLES/SR/TB[audio]"
