#!/bin/bash

header=$'<!DOCTYPE html>
<html>
  <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
  <body>
'

footer=$'</body></html>
'
SELF="$(dirname `realpath $0`)"
cd "$SELF"
outfile="./$(basename "$SELF").html"

exec 0>&-
exec 3>"$outfile"
echo "$header" >&3
cmark -t html readme.md >&3
echo "$footer" >&3
exec 3>&-

echo "Wrote to `realpath $SELF/$outfile`."

